### ISSUE TITLE
Insecure script URLs on Hugo Themes Website Demo

### ISSUE THREAD

**Issue by onedrawingperday** [garvincasimir/hugo-h5bp-simple#5]
Hello @garvincasimir 

I have noticed that your theme contains an insecure link to the jQuery library over here: https://github.com/garvincasimir/hugo-h5bp-simple/blob/7741bbce77c9fd66843ca102ae4ed118b42dd06e/layouts/partials/footer.html#L9

The Hugo Themes website is served under HTTPS and the above script causes a Mixed Content error.

Can you please look into providing a HTTPS link to jQuery? It would be preferable if you could host it in this repo or from a reputable CDN.

cc: @digitalcraftsman

**Comment by garvincasimir** [comment]
Hey @onedrawingperday, do the following changes resolve the issue? https://github.com/garvincasimir/hugo-h5bp-simple/blob/master/layouts/partials/footer.html

**Comment by onedrawingperday** [comment]
@garvincasimir 

The changes do fix this particular issue.

There is also another issue regarding the version of jQuery that is used in your theme, but I will open another issue about it.
