### ISSUE TITLE
jQuery version used is vulnerable to XSS

### ISSUE THREAD

**Issue by onedrawingperday** [garvincasimir/hugo-h5bp-simple#6]
@garvincasimir 

Continuing from #5 

The jQuery version you have included in your theme is vulnerable to XSS: https://snyk.io/test/npm/jquery/1.11.2

Please consider updating it to a more recent and secure version. Basically it needs to be a version greater than jQuery v. 3.0 see: https://security.stackexchange.com/questions/176512/is-there-a-base-version-of-jquery-which-has-no-xss-vulnerability

**Comment by garvincasimir** [comment]
@onedrawingperday what are your thoughts on just removing the included jQuery altogether and leave it to the theme users to add it in?

**Comment by onedrawingperday** [comment]
@garvincasimir 

The theme seems pretty simple so I suppose that you could remove jQuery without breaking functionality, it doesn't seem like it was needed in the first place.

**Comment by garvincasimir** [comment]
I created this a long time ago so I have no idea what the intent was. I will go ahead and remove jQuery.

**Comment by garvincasimir** [comment]
Removed in latest commit
